#############################  Runtime  #############################

# Reasonable concurrency to avoid rate-limiting small hosts.
max_concurrency = 14

# File extensions to scan
extensions = ["c", "h", "md", "html", "txt"]

#############################  Requests  ############################

# Accepted status codes
# - Include 429 (Too Many Requests) to avoid marking throttled links as dead.
accept = ["100..=103", "200..=299", "429"]

# Retry each request a few times on transient network errors
max_retries = 2
retry_wait_time = 2

# Timeout per request in seconds
timeout = 60

#############################  Exclusions  ##########################

exclude = [
  '^https?://sys/file$',
  '^file://.*',
  '^https?://(www\.)?badges\.debian\.net/.*$',
  '^https?://(www\.)?repology\.org/.*$',
  '^https?://scan\.coverity\.com/.*$',
  '^https?://(www\.)?img\.shields\.io/.*$',
  '^https?://(www\.)?fossies\.org/.*$',
  '^https?://(www\.)?adobe\.com.*$',
  '^https?://(www\.)?google\.com.*$',
  '^https?://(www\.)?forum\.vmssoftware\.com/.*$',
  '^http://vim\.sourceforge\.net/scripts/script\.php\?script_id=40$',
  '^https://is\.gd/.*$',
  '^https://wiki\.contextgarden\.net/Vim$',
  '^https://github\.com/you/foobar\.git$',
  '^https?://flatassembler\.net',
  '^https?://www\.fleiner\.com/vim/download.html',

  # Errors in \./lang/README\.zh_cn\.txt
  # CJK comma/preiod treat as url string\.
  '^https?://github\.com/vim/vim%E3%80%82',
  '^https?://github\.com/vim/vim-win32-installer/releases%E3%80%82',
  '^https?://github\.com/vim/vim/tags%E3%80%82',
  # Errors in \./README\.md
  # 403 auth
  '^https?://reddit\.com/r/vim',
  # Errors in \./runtime/doc/mbyte\.txt
  # FIXME find valid scim project site
  '^https?://www\.freedesktop\.org/wiki/Software/scim/',
  # Errors in \./runtime/doc/netbeans\.txt
  # FIXME find valid url on pida\.co\.uk
  # FIXME find valid site for a-a-p\.org (project alive?)
  '^https?://pida\.co\.uk/',
  '^https?://www\.a-a-p\.org/',
  # Errors in \./runtime/doc/vi_diff\.txt
  # FIXME find mail archive and what is written
  '^https?://www\.opengroup\.org/sophocles/show_mail\.tpl\?CALLER=show_archive\.tpl&source=L&listname=austin-review-l&id=1711',
  # Errors in \./runtime/spell/README\.txt
  # FIXME find valid site for a-a-p\.org (project alive?)
  '^https?://www\.a-a-p\.org/download\.html',
  # Errors in \./runtime/spell/README_en\.txt
  # 410 gone for app\.asspell\.net, find suitable url
  # FIXME find wordlist-devel project site
  '^https?://app\.aspell\.net/lookup',
  '^https?://lists\.sourceforge\.net/lists/listinfo/wordlist-devel',
  # Errors in \./src/INSTALLpc\.txt
  # FIXME 404 www\.upx\.org, find current project site (project alive?)
  '^https?://www\.upx\.org/',
]

# Lychee only reads UTF-8 files
exclude_path = [
  'src/po',
  'src/testdir',
]
